CREATE TABLE IF NOT EXISTS TGFILE (
    media_id BIGINT UNSIGNED PRIMARY KEY,
    dc_id TINYINT UNSIGNED NOT NULL,
    size BIGINT UNSIGNED NOT NULL,
    mime_type VARCHAR(255),
    file_name VARCHAR(255),
    thumb_size CHAR(1),
    is_restricted BOOLEAN DEFAULT FALSE,
    metadata JSON NOT NULL DEFAULT (JSON_OBJECT())
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FILE_LOCATION (
  bot_id BIGINT UNSIGNED NOT NULL,
  media_id BIGINT UNSIGNED NOT NULL,
  access_hash BIGINT NULL,
  file_reference BLOB NULL,
  PRIMARY KEY (bot_id, media_id),
  CONSTRAINT fk_file_ids_files FOREIGN KEY (media_id) REFERENCES TGFILE(media_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TGUSER (
    user_id BIGINT UNSIGNED PRIMARY KEY,
    join_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ban_date TIMESTAMP NULL,
    warns TINYINT UNSIGNED NOT NULL DEFAULT 0,
    preferred_lang VARCHAR(5) NOT NULL DEFAULT 'en',
    curt_op TINYINT UNSIGNED DEFAULT 0,
    op_id BIGINT DEFAULT 0,
    metadata JSON NOT NULL DEFAULT (JSON_OBJECT())
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_FILE (
  user_id BIGINT UNSIGNED NOT NULL,
  media_id BIGINT UNSIGNED NOT NULL,
  source_chat_id BIGINT NULL,
  source_msg_id BIGINT UNSIGNED NULL,
  added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata JSON NOT NULL DEFAULT (JSON_OBJECT()),
  PRIMARY KEY (user_id, media_id),
  CONSTRAINT fk_user_files_users FOREIGN KEY (user_id) REFERENCES TGUSER(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_user_files_files FOREIGN KEY (media_id) REFERENCES TGFILE(media_id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FILE_GROUP (
  group_id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_file_group_owner FOREIGN KEY (user_id) REFERENCES TGUSER(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FILE_GROUP_FILE (
  group_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  media_id BIGINT UNSIGNED NOT NULL,
  order_index INT UNSIGNED NOT NULL DEFAULT 0,
  metadata JSON NOT NULL DEFAULT (JSON_OBJECT()),
  PRIMARY KEY (group_id, user_id, media_id),
  CONSTRAINT fk_fg_group FOREIGN KEY (group_id) REFERENCES FILE_GROUP(group_id) ON DELETE CASCADE,
  CONSTRAINT fk_fg_user_file FOREIGN KEY (user_id, media_id) REFERENCES USER_FILE(user_id, media_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APP_CONFIG (
  k VARCHAR(64) PRIMARY KEY,
  v BLOB NOT NULL,
  type ENUM('bytes', 'bool', 'int', 'str', 'json') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
